// backend/services/pdfService.js
// Generates PDFs in-memory (Buffer) — stored in MongoDB, not on disk
// Render's ephemeral filesystem deletes files on restart, so we never write to disk
const PDFDocument = require('pdfkit');

// Generate legal document PDF → returns Buffer
exports.generateLegalDocPDF = (doc) => {
  return new Promise((resolve, reject) => {
    const pdfDoc = new PDFDocument({ margin: 60 });
    const chunks = [];

    pdfDoc.on('data', (chunk) => chunks.push(chunk));
    pdfDoc.on('end', () => resolve(Buffer.concat(chunks)));
    pdfDoc.on('error', reject);

    // Header
    pdfDoc.fontSize(10).fillColor('#666')
      .text(`Document No: ${doc.documentNumber}`, { align: 'right' });
    pdfDoc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'right' });
    pdfDoc.moveDown(2);

    // Title
    pdfDoc.fontSize(20).fillColor('#1a1a1a').font('Helvetica-Bold')
      .text(doc.title, { align: 'center' });
    pdfDoc.moveDown(0.5);

    // Document type badge
    const typeLabel = doc.documentType.replace(/_/g, ' ').toUpperCase();
    pdfDoc.fontSize(10).fillColor('#666').font('Helvetica')
      .text(typeLabel, { align: 'center' });
    pdfDoc.moveDown(1.5);

    // Divider
    pdfDoc.moveTo(60, pdfDoc.y).lineTo(550, pdfDoc.y).stroke('#ddd');
    pdfDoc.moveDown(1);

    // Content
    pdfDoc.fontSize(12).fillColor('#333').font('Helvetica')
      .text(doc.content, { align: 'left', lineGap: 6 });
    pdfDoc.moveDown(2);

    // Footer
    pdfDoc.moveTo(60, pdfDoc.y).lineTo(550, pdfDoc.y).stroke('#ddd');
    pdfDoc.moveDown(1);
    pdfDoc.fontSize(9).fillColor('#999')
      .text('Generated by LawLink — Legal Services Platform', { align: 'center' });

    pdfDoc.end();
  });
};

// Generate invoice PDF → returns Buffer
exports.generateInvoicePDF = (invoice) => {
  return new Promise((resolve, reject) => {
    const pdfDoc = new PDFDocument({ margin: 50 });
    const chunks = [];

    pdfDoc.on('data', (chunk) => chunks.push(chunk));
    pdfDoc.on('end', () => resolve(Buffer.concat(chunks)));
    pdfDoc.on('error', reject);

    // Header
    pdfDoc.fontSize(22).font('Helvetica-Bold').text('INVOICE', { align: 'center' });
    pdfDoc.moveDown(0.3);
    pdfDoc.fontSize(10).font('Helvetica').fillColor('#666')
      .text(`Invoice #: ${invoice.invoiceNumber}`, { align: 'right' });
    pdfDoc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'right' });
    pdfDoc.text(`Due: ${new Date(invoice.dueDate).toLocaleDateString()}`, { align: 'right' });
    pdfDoc.moveDown(1.5);

    // Line items table header
    const tableTop = pdfDoc.y;
    pdfDoc.fontSize(10).font('Helvetica-Bold').fillColor('#333');
    pdfDoc.text('Description', 50, tableTop, { width: 250 });
    pdfDoc.text('Hours', 310, tableTop, { width: 60, align: 'right' });
    pdfDoc.text('Rate', 380, tableTop, { width: 70, align: 'right' });
    pdfDoc.text('Amount', 460, tableTop, { width: 80, align: 'right' });
    pdfDoc.moveDown(0.5);

    pdfDoc.moveTo(50, pdfDoc.y).lineTo(550, pdfDoc.y).stroke('#ddd');
    pdfDoc.moveDown(0.5);

    // Line items
    pdfDoc.font('Helvetica').fillColor('#555');
    invoice.lineItems.forEach(item => {
      const y = pdfDoc.y;
      pdfDoc.text(item.description, 50, y, { width: 250 });
      pdfDoc.text(item.hours.toString(), 310, y, { width: 60, align: 'right' });
      pdfDoc.text(`Rs.${item.ratePerHour}`, 380, y, { width: 70, align: 'right' });
      pdfDoc.text(`Rs.${item.amount}`, 460, y, { width: 80, align: 'right' });
      pdfDoc.moveDown(0.8);
    });

    // Total
    pdfDoc.moveDown(0.5);
    pdfDoc.moveTo(50, pdfDoc.y).lineTo(550, pdfDoc.y).stroke('#ddd');
    pdfDoc.moveDown(0.5);
    pdfDoc.fontSize(14).font('Helvetica-Bold').fillColor('#1a1a1a');
    pdfDoc.text(`Total: Rs.${invoice.totalAmount}`, { align: 'right' });

    // Footer
    pdfDoc.moveDown(3);
    pdfDoc.fontSize(9).font('Helvetica').fillColor('#999')
      .text('Generated by LawLink — Legal Services Platform', { align: 'center' });

    pdfDoc.end();
  });
};
